### ISSUE TITLE
dichtsbijzijnde stations

### ISSUE THREAD

**Issue by markimarc** [ovdingen/spoor.app#1]
Is het mogelijk om bij de dichtsbijzijnde stations meer als output te hebben?
Nu staan er maar de 3 dichtsbijzijnde stations, terwijl er meer makkelijker zou kunnen zijn.

Mijn voorstel is minimaal 5.

**Comment by brandsjek** [comment]
Akkoord, 5 is de sweetspot tussen te weinig en te veel mijns inziens. Hier gaat vanavond een commitje tegenaan.

**Comment by brandsjek** [comment]
gefixt in stations-api

**Comment by markimarc** [comment]
Ik krijg er nog steeds 3.
![screen shot 2018-05-20 at 13 54 00](https://user-images.githubusercontent.com/6544290/40278646-78ce4250-5c35-11e8-8405-5849ec5c90b9.png)

**Comment by brandsjek** [comment]
Gefixt. Geen bug, eigen infra was nog niet up2date.
