### ISSUE TITLE
Vertrektijden station met vertraging

### ISSUE THREAD

**Issue by markimarc** [ovdingen/spoor.app#2]
Graag de mogelijkheid toevoegen zodat je ook de vertraging van de trein(en) kan zien. Net zoals bijvoorbeeld de Reisplanner Xtra van NS. 

Dit aangezien je nu niet kan zien of de trein vertraging heeft of niet.

Het is mij wel gelukt om dit toe te voegen bij de trein(en) zelf.

**Comment by brandsjek** [comment]
49d193a7d1866b2c0b5112e3034a76dc6ff33ed8

**Comment by markimarc** [comment]
@Flippylosaurus
